<?php namespace AccountHon\Repositories\Workshops;


use AccountHon\Entities\Workshops\ModelWorkshop;
use AccountHon\Repositories\BaseRepository;

/**
 * Created by PhpStorm.
 * User: anwarsarmiento
 * Email: asarmiento@sistemasamigables.com
 * Date: 6/12/16
 * Time: 22:36
 */
class ModelWorkshopRepository extends BaseRepository
{

    /**
     * @return mixed
     */
    public function getModel()
    {
       return new ModelWorkshop(); // TODO: Implement getModel() method.
    }

    public function allFilterInst()
    {
        return $this->newQuery()->whereHas('brand',function ($q){
            $q->where('school_id',userSchool()->id);
        })->get(); // TODO: Change the autogenerated stub
    }
}